{% set name = "grayskull" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbbefd3cbc240c74f22322fabf7862bd36108ac9b4c42a5121b4e68636eab0af

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - colorama
    - rapidfuzz >=0.7.6
    - pip
    - progressbar2
    - python >=3.7
    - requests
    - ruamel.yaml >=0.15.3
    - ruamel.yaml.jinja2
    - setuptools >=30.3.0
    - stdlib-list
    - git

test:
  imports:
    - grayskull
  commands:
    - pip check
    - grayskull --help
    - greyskull --help
  requires:
    - pip

about:
  home: https://pypi.org/project/grayskull/
  summary: Project to generate recipes for conda.
  dev_url: https://github.com/marcelotrevisani/grayskull
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
