{% set name = "grayskull" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 826702c4165731c044d30af49230a761ffc753bda8f6be38be9be642fd367037

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
    - conda-grayskull = grayskull.__main__:main
    - conda-greyskull = grayskull.__main__:main

outputs:
  - name: grayskull
    script: build_base.bat  # [win]
    script: build_base.sh   # [unix]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - setuptools_scm
        - toml
        - wheel
      run:
        - python
        - beautifulsoup4
        - colorama
        - conda-souschef >=2.2.3
        - packaging >=21.3
        - pip
        - pkginfo
        - progressbar2 >=3.53.0
        - rapidfuzz >=1.7.1
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - semver >=2.13.0,<3.0.0
        - setuptools >=30.3.0
        - stdlib-list
        - tomli
        - tomli-w
    test:
      imports:
        - grayskull
      requires:
        - pip
      # Test commands are in scripts run_test.bat and run_test.sh

  - name: greyskull
    build:
      noarch: generic
    requirements:
      host:
        - pip
        - python
        - setuptools
        - setuptools_scm
        - toml
        - wheel
      run:
        - python
        - {{ pin_subpackage('grayskull', max_pin="x.x.x") }}
    test:
      imports:
        - grayskull
      requires:
        - pip
      # Test commands are in scripts run_test.bat and run_test.sh

about:
  home: https://github.com/conda/grayskull
  summary: Project to generate recipes for conda.
  description: |
    Grayskull is an automatic conda recipe generator.
    The main goal of this project is to generate concise recipes for conda-forge. 
    The Grayskull project was created with the intention to eventually replace conda skeleton.
  dev_url: https://github.com/conda/grayskull
  doc_url: https://github.com/conda/grayskull/blob/main/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
  skip-lints:
    - python_build_tool_in_run
    - missing_pip_check
