{% set name = "grayskull" %}
{% set version = "2.9.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3d8afd8ccd8dce1f6f3c75dcf1697a72c1a41fbdf64233d1b958514265da26a

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python

outputs:
  - name: grayskull
    build:
      script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
      entry_points:
        - grayskull = grayskull.__main__:main
        - greyskull = grayskull.__main__:main
        - conda-grayskull = grayskull.__main__:main
        - conda-greyskull = grayskull.__main__:main
    requirements:
      host:
        - pip
        - python
        - setuptools >=61
        - setuptools_scm >=6.2
        - toml
        - wheel
      run:
        - python
        - beautifulsoup4
        - colorama
        - conda-souschef >=2.2.3
        - packaging >=21.3
        - pip
        - pkginfo
        - progressbar2 >=3.53.0
        - rapidfuzz >=3.0.0
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - setuptools >=30.3.0
        - stdlib-list
        - tomli  # [py<311]
        - tomli-w

    {% set deselect_tests = [
      "--deselect=tests/test_pypi.py::test_injection_distutils_pytest",
      "--deselect=tests/test_pypi.py::test_mypy_deps_normalization_and_entry_points",
      "--deselect=tests/test_pypi.py::test_sequence_inside_another_in_dependencies"
    ]%}
    test:
      source_files:
        - tests
        - grayskull
        - pyproject.toml
        - pytest.ini
      imports:
        - grayskull
        - grayskull.base
        - grayskull.strategy
      requires:
        - pip
        - pytest
        - numpy
        - pytest-mock
      commands:
        - pip check
        - grayskull --help
        - greyskull --help
        - pytest -v {{ deselect_tests | join(" ") }}

  - name: greyskull
    build:
      noarch: generic
    requirements:
      host:
        - pip
        - python
        - setuptools
        - setuptools_scm
        - toml
        - wheel
      run:
        - python
        - {{ pin_subpackage('grayskull', max_pin="x.x.x") }}
    test:
      imports:
        - grayskull
      commands:
        - grayskull --help
        - greyskull --help

about:
  home: https://github.com/conda/grayskull
  summary: Project to generate recipes for conda.
  description: |
    Grayskull is an automatic conda recipe generator.
    The main goal of this project is to generate concise recipes for conda-forge.
    The Grayskull project was created with the intention to eventually replace conda skeleton.
  dev_url: https://github.com/conda/grayskull
  doc_url: https://github.com/conda/grayskull/blob/main/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
  skip-lints:
    - python_build_tool_in_run
    - missing_pip_check
