{% set name = "grayskull" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6ccbcc7455c08b68d95ed880fe486d87ad321ee483ccb375bfd8163c19a0fdfa

  - url: https://github.com/conda/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2ea9376e1aca8147e1329d96a451a27ceb00aa2a86e2026e13b16184974349ab
    folder: gh_src

build:
  number: 1
  skip: true  # [py<310]

requirements:
  host:
    - python

outputs:
  - name: grayskull
    build:
      script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
      entry_points:
        - grayskull = grayskull.__main__:main
        - greyskull = grayskull.__main__:main
        - conda-grayskull = grayskull.__main__:main
        - conda-greyskull = grayskull.__main__:main
    requirements:
      host:
        - pip
        - python
        - setuptools >=61
        - setuptools_scm >=6.2
        - toml
        - wheel
      run:
        - python
        - beautifulsoup4
        - colorama
        - conda-souschef >=3.0.1
        - packaging >=21.3
        - pip
        - pkginfo
        - progressbar2 >=3.53.0
        - rapidfuzz >=3.0.0
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - setuptools >=30.3.0
        - stdlib-list
        - tomli  # [py<311]
        - tomli-w

    # E AssertionError: assert [pip, python >=3.6] == ['argparse', ... 'traceback2']
    # E Right contains 10 more items, first extra item: 'atomicwrites>=1.0;sys_platform=="win32"'
    {% set deselect_tests = [
      "--deselect=gh_src/tests/test_pypi.py::test_injection_distutils_pytest",
      "--deselect=gh_src/tests/test_pypi.py::test_mypy_deps_normalization_and_entry_points",
      "--deselect=gh_src/tests/test_pypi.py::test_sequence_inside_another_in_dependencies",
      "--deselect=gh_src/tests/cli/test_cli_recipes.py::test_loop_deps_nipy_and_maintainers",
      # httplib2shim=0.0.3 Don`t have a license file in PyPI
      "--deselect=gh_src/tests/cli/test_cli_cmds.py::test_license_discovery",
      "--deselect=gh_src/tests/test_pypi.py::test_compose_test_section_with_console_scripts"
    ]%}
    {% set deselect_tests_win = [
      "--deselect=gh_src/tests/test_py_toml.py::test_poetry_langchain_snapshot",
      "--deselect=gh_src/tests/test_pypi.py::test_replace_slash_in_imports",
      "--deselect=gh_src/tests/test_pypi.py::test_create_recipe_from_local_sdist",
      # httplib2shim=0.0.3 Don`t have a license file in PyPI
      "--deselect=gh_src/tests/cli/test_cli_cmds.py::test_license_discovery"
    ]%}
    test:
      source_files:
        - gh_src/tests
        - gh_src/grayskull
        - gh_src/pyproject.toml
        - gh_src/pytest.ini
      imports:
        - grayskull
        - grayskull.base
        - grayskull.cli
        - grayskull.config
        - grayskull.license
        - grayskull.strategy
        - grayskull.utils
      requires:
        - pip
        - pytest
        - numpy
        - pytest-xdist
        - pytest-mock
      commands:
        - pip check
        - grayskull --help
        - greyskull --help
        - pytest -ra -v -n auto {{ deselect_tests | join(" ") }} # [not win]
        - pytest -ra -v -n auto {{ deselect_tests | join(" ") }} {{ deselect_tests_win | join(" ") }} # [win]

  - name: greyskull
    build:
      noarch: generic
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('grayskull', exact=True) }}
    test:
      imports:
        - grayskull
      commands:
        - grayskull --help
        - greyskull --help

about:
  home: https://github.com/conda/grayskull
  summary: Project to generate recipes for conda.
  description: |
    Grayskull is an automatic conda recipe generator.
    The main goal of this project is to generate concise recipes for conda-forge.
    The Grayskull project was created with the intention to eventually replace conda skeleton.
  dev_url: https://github.com/conda/grayskull
  doc_url: https://github.com/conda/grayskull/blob/main/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
  skip-lints:
    - python_build_tool_in_run
    - missing_pip_check
