{% set name = "grayskull" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b30e93ab1129b63ed86abcf7e8dde491269017269cf6c850cf09328e4d48c9d6

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - colorama
    - rapidfuzz
    - pip
    - progressbar2
    - python >=3.7
    - requests
    - ruamel.yaml >=0.15.3
    - ruamel.yaml.jinja2
    - setuptools >=30.3.0
    - stdlib-list
    - git

test:
  imports:
    - grayskull
  commands:
    - pip check
    - grayskull --help
  requires:
    - pip

about:
  home: https://pypi.org/project/grayskull/
  summary: Project to generate recipes for conda.
  dev_url: https://github.com/marcelotrevisani/grayskull
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
